src/Traits/HasPageShield.php
=> Fixes issue #17

src/Commands/Concerns/CanManipulateFiles.php
Using "/" as directory separator throws "mkdir(): File exists error" on Windows so it should be replaced with DIRECTORY_SEPARATOR constant.
=> directory seperator fix

src/Commands/MakeShieldSuperAdminCommand.php
This allows you to provide a `user` argument to the `shield:super-admin` command to skip the interactive portion. This is entirely optional but can be used like so:
```
php artisan shield:super-admin --user=1
```
=> Allow user option for shield:super-admin command

config/filament-shield.php, src/Commands/MakeShieldDoctorCommand.php, src/Resources/RoleResource.php, src/Support/Utils.php
This PR adds a config option which allows the user to quickly and easily turn off the navigation group (slotting the navigation item for Shield in with the rest of the navigation items). The new section of the config looks like this:
```
'shield_resource' => [
'slug' => 'shield/roles',
'navigation_sort' => -1,
'navigation_badge' => true,
'navigation_group' => true,
],
```
=> Config option to easily turn off navigation group

src/Commands/MakeShieldSeederCommand.php, src/Commands/MakeShieldSuperAdminCommand.php, src/FilamentShield.php, src/FilamentShieldServiceProvider.php, src/Resources/RoleResource.php, src/Resources/RoleResource/Pages/CreateRole.php, src/Resources/RoleResource/Pages/EditRole.php
When extend role or permission model, we should use the model specified in the config so that we do not get errors in filament dashboard or commands.
Example extend, uuid based role and permission https://spatie.be/docs/laravel-permission/v5/advanced-usage/uuid
=> feat: use config models

README.md
The text explaining is referencing the "PostResource", but the example was showing the "Role Resource"
=> Typo in example for custom permission

src/Support/Utils.php
A resource's navigation sort is nullable (see `\BezhanSalleh\FilamentShield\Resources\RoleResource::getNavigationSort`), so the util should also support `null`. This will use Filament's default sorting.
=> refactor: make getResourceNavigationSort nullable

src/FilamentShield.php
current check for class name is a loosely check as it checks for `endsWith`, this PR looks to fix this
in my app there is this permission "view_Search"
and having these pages (from `Filament::getPages()`)
```php
[
0 => "RyanChandler\FilamentProfile\Pages\Profile",
1 => "App\Filament\Pages\Dashboard",
2 => "App\Filament\Pages\ManageSearch",
3 => "App\Filament\Pages\ManageSite",
4 => "App\Filament\Pages\MarketValue\ListCars",
5 => "App\Filament\Pages\MarketValue\ShowCar",
6 => "App\Filament\Pages\Search"
];
```
the current code only take the first class name thats end with "Search" resulted to this
**after fix**
=> fix getting label name from wrong class

stubs/DefaultPolicy.stub, stubs/UserPolicy.stub
This PR removes invalid PHPDoc return types from the stubs.
Return type hints added previously are excellent, but currently the docblocks of the generated policies don't match those, and cause errors in static analysis. PHPStan for example throws the following error:
```
19     PHPDoc tag @return with type bool|Illuminate\Auth\Access\Response is not subtype of native type bool.
```
=> ⚰️ Remove invalid PHPDoc from stubs

src/Commands/MakeShieldDoctorCommand.php, src/Commands/MakeShieldGenerateCommand.php, src/Commands/MakeShieldInstallCommand.php, src/Commands/MakeShieldPublishCommand.php, src/Commands/MakeShieldSeederCommand.php, src/Commands/MakeShieldSuperAdminCommand.php, src/Commands/MakeShieldUpgradeCommand.php
Other functions not working. Total command exit.
=> php exit function replace to return

src/Traits/HasPageShield.php
from filament [v3.0.57](https://github.com/filamentphp/filament/blob/v3.0.57/packages/panels/src/Resources/Pages/Page.php#L130) they overriding shouldRegisterNavigation and adding $parameters into it.
=> add $parameters to shouldRegisterNavigation

README.md, composer.json
=> drop support for spatie permission 5.0 and add support for 6.0

src/FilamentShield.php
Packages such as filament-apexcharts use private functions for getHeading() etc, which means this doesn't work.
This fixes that.
=> Some other widget packages use private classes for widgets - this fixes that

stubs/ShieldSeeder.stub
fix: Using current guard name in permission creation.
=> Updating ShieldSeeder stub

config/filament-shield.php, src/Commands/Concerns/CanGeneratePolicy.php
My current application requires the policies for filament to be stored in another location than default. This PR makes the policy path configurable.
=> Make policy path configurable

src/Commands/MakeShieldGenerateCommand.php, src/FilamentShield.php, src/Resources/RoleResource.php
Fixes #304 & some performance improvments.
=> fixes and improvements

src/Commands/MakeShieldSeederCommand.php
This PR will add an `--option` option to the shield:seeder command.
This option supports two choices:
1. `permissions_via_roles`: Only generate the seeder with permissions via roles
2. `direct_permissions`: Only generate the seeder with direct permissions
Will fix #309
=> Add option to shield:seeder command to only generate direct permissions

src/Commands/MakeShieldSuperAdminCommand.php
Not all User models use 'id' as the primary key. For example, mine is 'uuid'. 
Using `->getKey()` automatically gets the primary key value for us to use in the options table.
=> Don't use hardcoded primary key name

src/Traits/HasPageShield.php
In case you are use a Cluster, the item will show in the navigation even though all the pages inside are without access, clicking on the item and navigating will bring an error.
Since the item is hidden by the canAccess method check I added it, now it will work smoothly.
T.Y
=> Overide canAccess that will point to canView

resources/lang/pl/filament_shield.php
=> feat: add Polish translation

README.md
Update Role Policy and Custom folder structure parts of the Doc following the changes introduced by Laravel 11 in particular those concerning the [Service Providers](https://laravel.com/docs/11.x/releases#service-providers).
=> Update Doc for Laravel 11 (Role Policy and Custom folder structure)

src/Resources/RoleResource.php
Thank you for providing the fixes in release v3.3.2
This PR addresses the issue where `Utils::getTenantModel()` could return `null`, leading to the "Class name must be a valid object or a string" error page when trying to edit roles. The solution includes a null check, ensuring that if getTenantModel() returns null, the code safely returns an empty collection.
=> fix: Add error handling for team options when teams are not used

src/FilamentShield.php
Fix for Issue #471:
•	Added a check to ensure that the getHeading method returns a non-null value before using it.
•	Removed redundant check for TableWidget in the heading validation logic, as it’s already handled in the existing conditions.
This should address the issue with heading retrieval in widgets
=> [Fix] Handles Widget Permission Labels through `$heading`

src/FilamentShield.php
[`getAllResourcePermissions()`](https://github.com/bezhanSalleh/filament-shield/blob/3.x/src/FilamentShield.php#L349) is currently running the already pluralized [`Resource::getPluralModelLabel()`](https://github.com/filamentphp/filament/blob/3.x/packages/panels/src/Resources/Resource.php#L521) through `->plural()` again which causes issues in non-english languages. See the german example below.
```php
->prepend(
str($resourceEntity['fqcn']::getPluralModelLabel())
->plural()
->title()
->append(' - ')
->toString()
```
German example:
| Singular| Plural| Expected output| Actual output|
|--------|--------|--------|--------|
| Kunde| Kunden | Kunden ✅| Kundens ❌|
| Lieferant| Lieferanten| Lieferanten ✅ | Lieferantens ❌|
English example:
| Singular| Plural| Expected output| Actual output| …
=> Remove double-pluralization from `getAllResourcePermissions`

src/Resources/RoleResource.php
Hi.
When Tenant is enable, the unique role name have to be unique in the tenant.
So my proposition is to add a modifyRuleUsing closure to add a where clause when tenant is enabled.
Regards.
=> [bug] Add optional Tenant to Role name unique rule

src/FilamentShieldServiceProvider.php
Updated the RolePolicy registration in FilamentShieldServiceProvider.php to use the dynamic namespace from `Utils::getPolicyNamespace()`. This change allows users to move their policies directory without breaking the RolePolicy registration, making the codebase more flexible and consistent.
Without this change, if someone moves their policies, they must also move the RolePolicy, otherwise it won't be registered.
=> refactor: Use dynamic policy namespace for RolePolicy registration

src/Traits/HasWidgetShield.php
Fixing widget permissions doesn't applies on super_admin
Descriptions:
The current implementation includes an OR condition that grants the super_admin access to view all widgets, even if there are permissions set to hide widgets for the super_admin.
=> [Fix] widget permissions on super admin

src/FilamentShield.php
Thanks for a great package man. I bumped into a situation where I have a filament resource called `ResourceGroupResource`, which generates empty permissions, as it removes everything before the first instance of `Resource`. This fix allows for filament resources having names that includes the keyword `Resource`.
Thanks.
=> fix: allow Resource to be part of the Filament Resource name

resources/lang/es/filament-shield.php
From: "Forzar elminación"
To: "Eliminar eliminación"
=> Fix typo in Spanish translation for force delete action
