bezhanSalleh/filament-shield

- README.md
- resources/lang/pt_BR/filament-shield.php
I'm sorry for the mistake. Now with all keys.
> Add Brazilian Portuguese

- resources/lang/pt_BR/filament-shield.php
> Fix two translations keys

- resources/lang/tr/filament-shield.php
> Add support for Turkish (tr) translation

- resources/lang/es/filament-shield.php
All right, I have added the Spanish translations based on the latest version 1.1.6 :)
> Add spanish translations

- resources/lang/id/filament-shield.php
just added Indonesian translations.
> added Indonesian translations.

- resources/lang/fr/filament-shield.php
> [Fr] Translate new phrases

- resources/lang/es/filament-shield.php
Updated to currently latest version of filament-shield (31 july 13:19 GMT-5).
Updated Spanish translation
> Spanish translation update

- src/Commands/MakeShieldGenerateCommand.php
This PR adds an option to the `shield:generate` command that allows you to override the `generator.option` config value. It is used as follows:
```
php artisan shield:generate --option=permissions
php artisan shield:generate --option=policies
php artisan shield:generate --option=policies_and_permissions
```
> Add flag to shield:generate to override generator.option config value

- README.md
- src/Commands/MakeShieldDoctorCommand.php
- src/Commands/MakeShieldUpgradeCommand.php
> Improve Command Section of README

- src/Commands/Concerns/CanManipulateFiles.php
- src/Commands/MakeShieldSeederCommand.php
- src/FilamentShieldServiceProvider.php
- stubs/ShieldSeeder.stub
Adds new command `shield:seeder`
> adds new command 

- config/filament-shield.php
- src/Resources/RoleResource.php
- src/Support/Utils.php
> adds the ability to set global search status & fixes #118

- src/Commands/MakeShieldGenerateCommand.php
- src/Commands/MakeShieldInstallCommand.php
This PR adds an optional --minimal flag to the Install and Generate commands to allow for showing less output in the console.
> Feature: Implement optional --minimal flag

- resources/lang/ro/ro.php
> ro language

- README.md
Was just reading about this package and noticed a couple of typos in the readme so thought I'd submit a PR.
> Fix minor typo and grammar

- resources/lang/hu/filament-shield.php
> feat: add hungarian translation

- src/Resources/RoleResource.php
> Fix role resource card columns

- config/filament-shield.php
- src/Commands/Concerns/CanManipulateFiles.php
- src/Commands/MakeShieldDoctorCommand.php
- src/Commands/MakeShieldPublishCommand.php
- src/FilamentShieldServiceProvider.php
- src/Support/Utils.php
makes it possible now to easily customize the RoleResource.
> added publish command to provide an easy way to customize Shield RoleResource

- stubs/DefaultPolicy.stub
- stubs/UserPolicy.stub
this pull request adds the bool return type to policies stubs to be in line with new laravel 10 return types
> Policies return type

- resources/lang/filament-shield_pt_PT.php
this is the portuguese from portugal translation
> Create filament-shield.php in folder pt_PT

- resources/lang/cs/filament-shield.php
Hello
I prepared czech translations for your great filament plugin. 
rockero.cz
> Add czech translations

- src/Support/Utils.php
> fixes #274

- composer.json
> drop support for spatie permission 6.0

- config/filament-shield.php
> Fixes App\Policies\Role doesn't exists

- stubs/DefaultPolicy.stub
Follows the Laravel default policy style.
> Remove unnecessary PHPDoc

- src/Resources/RoleResource.php
Fixed Tab bug in Chinese language. #357
> Fixed Tab bug in chinese language

- src/Resources/RoleResource.php
Just remove an useless blank row
> fix: remove blank row

- src/FilamentShield.php
> Fixes tenant id type hint for when its uuid or string

- README.md
Minimal fix for documentation Page Hooks examples
> Fix example methods on Pages Hooks docs

- config/filament-shield.php
- src/Resources/RoleResource.php
- src/Support/Utils.php
Added support for customizabile sub navigation position
> Added support for customizabile sub navigation position

- src/FilamentShield.php
> Fixes #560

- resources/lang/cs/filament-shield.php
- resources/lang/sk/filament-shield.php
Add missing translations to 4.x too.
> Add missing CZ and SK translations (4.x)

- src/Commands/Concerns/CanManipulateFiles.php
> [Fix] Tenancy Part of `shield:setup` command
